### ISSUE TITLE
Where to add service_email

### ISSUE THREAD

**Issue by ParadoxNL** [lordcoste/analytics-s2s#1]
Can you be more specific on where to add service_email, as i cannot find the place to add it

> (5) Visit https://www.google.com/analytics/web/#management/Accounts/
> 
> Add the 'service_email' as a user to the properties of each account that you would like authorize access
- Robert

**Comment by lordcoste** [comment]
Hi, I'll try to explain but, my account is not in english so i'm not sure of the translation. 
1.  Visit that url
2.  You should see a list of your registered account (or just one if you only have analytics for one website)
3.  Click on the account and you should see a tab menu: "Properties, Users, Filters, Source of data, etc.."
4.  Click on "Users"
5.  Click on "+ New user"
6.  Insert the email address.

Let me know if is clear ;)

Il giorno sabato 4 maggio 2013, alle ore 00:16, ParadoxNL ha scritto: 

> https://www.google.com/analytics/web/#management/Accounts/

**Comment by ParadoxNL** [comment]
Awesome that did the trick!
